[package]
name = "manette"
version = "0.1.0"
authors = ["Paul Ezvan <paul@ezvan.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
